version: '3'
services:
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    depends_on:
      - frontend
      - api

  frontend:
    build: ./l2dFrontend

  api:
    build: .
    depends_on:
      - db
    env_file:
      - .env
    environment:
      - CHATLLM_DB_URL=postgresql://postgres:password@db/myapp
    volumes:
      - ./${GCP_AI_SA_CREDENTIAL_PATH:-gcp_cred-ai.json}:/app/gcp_cred-ai.json
      - ./chroma_db:/app/chroma_db
      - ./data:/app/data
      - ./chat_data:/app/chat_data

  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=myapp
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
  chat_data:
