"""create db

Revision ID: 06726734bcd0
Revises: 
Create Date: 2024-11-24 20:04:02.220880

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '06726734bcd0'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chatId', sa.String(), nullable=False),
    sa.Column('systemMessage', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chats_chatId'), 'chats', ['chatId'], unique=True)
    op.create_table('chat_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('dateTime', sa.DateTime(timezone=True), nullable=False),
    sa.Column('chat_id', sa.Integer(), nullable=False),
    sa.CheckConstraint("role IN ('user', 'ai', 'system')", name='check_role'),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('message_attachments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mimeType', sa.String(), nullable=False),
    sa.Column('blobName', sa.String(), nullable=False),
    sa.Column('baseDataPath', sa.String(), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['chat_messages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('message_context',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['chat_messages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('message_context')
    op.drop_table('message_attachments')
    op.drop_table('chat_messages')
    op.drop_index(op.f('ix_chats_chatId'), table_name='chats')
    op.drop_table('chats')
    # ### end Alembic commands ###
