"""empty message

Revision ID: 2a754c19107f
Revises: ae47c8e42445
Create Date: 2025-01-23 06:50:52.112270

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a754c19107f'
down_revision: Union[str, None] = 'ae47c8e42445'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_proifile_chat_records', sa.Column('summory', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_proifile_chat_records', 'summory')
    # ### end Alembic commands ###
