"""fix to int on facebookId comumn and add user summory column

Revision ID: 3812991711e4
Revises: dad73ad832f9
Create Date: 2024-11-27 03:39:00.016572

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3812991711e4'
down_revision: Union[str, None] = 'dad73ad832f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profile', sa.Column('personalizationSummoryLastUpdate', sa.DateTime(), nullable=False))
    op.alter_column('user_profile', 'facebookId',
               existing_type=sa.VARCHAR(),
               type_=sa.Integer(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_profile', 'facebookId',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.drop_column('user_profile', 'personalizationSummoryLastUpdate')
    # ### end Alembic commands ###
