"""alter profile key pair

Revision ID: ae47c8e42445
Revises: b6f6c198098a
Create Date: 2025-01-16 21:36:13.012491

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae47c8e42445'
down_revision: Union[str, None] = 'b6f6c198098a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('message_context')
    op.drop_column('chats', 'systemMessage')
    op.add_column('user_profile', sa.Column('personalizationSummory', sa.String(), nullable=True))
    op.alter_column('user_profile', 'facebookId',
               existing_type=sa.VARCHAR(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('user_profile', 'personalizationSummoryLastUpdate',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('user_proifile_chat_records', 'chatId',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_index(op.f('ix_user_proifile_chat_records_chatId'), 'user_proifile_chat_records', ['chatId'], unique=False)
    op.create_index(op.f('ix_user_proifile_chat_records_profile_id'), 'user_proifile_chat_records', ['profile_id'], unique=False)
    op.create_index(op.f('ix_user_proifile_sessions_sessionToken'), 'user_proifile_sessions', ['sessionToken'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_proifile_sessions_sessionToken'), table_name='user_proifile_sessions')
    op.drop_index(op.f('ix_user_proifile_chat_records_profile_id'), table_name='user_proifile_chat_records')
    op.drop_index(op.f('ix_user_proifile_chat_records_chatId'), table_name='user_proifile_chat_records')
    op.alter_column('user_proifile_chat_records', 'chatId',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('user_profile', 'personalizationSummoryLastUpdate',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.alter_column('user_profile', 'facebookId',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.drop_column('user_profile', 'personalizationSummory')
    op.add_column('chats', sa.Column('systemMessage', sa.VARCHAR(), nullable=False))
    op.create_table('message_context',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('value', sa.VARCHAR(), nullable=False),
    sa.Column('message_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['chat_messages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
