"""fix nullable personalationSummory

Revision ID: b6f6c198098a
Revises: 3812991711e4
Create Date: 2024-11-27 19:46:36.164254

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b6f6c198098a'
down_revision: Union[str, None] = '3812991711e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profile', sa.Column('personalizationSummory', sa.String(), nullable=True))
    op.alter_column('user_profile', 'facebookId',
               existing_type=sa.VARCHAR(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('user_profile', 'personalizationSummoryLastUpdate',
               existing_type=sa.DATETIME(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_profile', 'personalizationSummoryLastUpdate',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.alter_column('user_profile', 'facebookId',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.drop_column('user_profile', 'personalizationSummory')
    # ### end Alembic commands ###
