"""facebook

Revision ID: d1b101e385a2
Revises: 06726734bcd0
Create Date: 2024-11-25 04:52:04.968962

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd1b101e385a2'
down_revision: Union[str, None] = '06726734bcd0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('facebookId', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_profile_facebookId'), 'user_profile', ['facebookId'], unique=False)
    op.create_index(op.f('ix_user_profile_username'), 'user_profile', ['username'], unique=False)
    op.create_table('user_proifile_chat_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('chatId', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['chatId'], ['chats.chatId'], ),
    sa.ForeignKeyConstraint(['profile_id'], ['user_profile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_proifile_chat_records')
    op.drop_index(op.f('ix_user_profile_username'), table_name='user_profile')
    op.drop_index(op.f('ix_user_profile_facebookId'), table_name='user_profile')
    op.drop_table('user_profile')
    # ### end Alembic commands ###
