"""profile session

Revision ID: dad73ad832f9
Revises: d1b101e385a2
Create Date: 2024-11-26 02:38:52.055034

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dad73ad832f9'
down_revision: Union[str, None] = 'd1b101e385a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_proifile_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('sessionToken', sa.String(), nullable=False),
    sa.Column('expire', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['user_profile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index('ix_user_profile_username', table_name='user_profile')
    op.drop_index('ix_user_profile_facebookId', table_name='user_profile')
    op.create_index(op.f('ix_user_profile_facebookId'), 'user_profile', ['facebookId'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_profile_facebookId'), table_name='user_profile')
    op.create_index('ix_user_profile_facebookId', 'user_profile', ['facebookId'], unique=False)
    op.create_index('ix_user_profile_username', 'user_profile', ['username'], unique=False)
    op.drop_table('user_proifile_sessions')
    # ### end Alembic commands ###
